mig:
	python3 manage.py makemigrations
	python3 manage.py migrate

beat:
	celery -A root beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler

celery:
	celery -A root worker -l INFO